### ISSUE TITLE
Can not submit survey

### ISSUE THREAD

**Issue by nadeemshafique** [tpartner/LimeSurvey-Multiple-Choice-Dropdown#1]
When I use "Multiple-Choice-Dropdown" everything works perfect but when I click on submit button at the end of survey. Submission get stuck.

**Comment by tpartner** [comment]
I cannot reproduce that. Please give more details about the environment - LimeSurvey version, browser, etc.

Did you disable AJAX in the theme options?

Did you try the demo survey?

**Comment by nadeemshafique** [comment]
Dear tpartner,
Thank you very much for your guidance. You are absolutely right when I change browser from Chrome to Edge, it works perfectly. And when I change theme bootswatch to SkelVanilla it works perfectly on both Chorme and Edge. I am using LimeSurvey Version 3.19.3+191023

Once again thank you very much for providing such a nice and much awaited feature to limesurvey
